service:
  logging_level:                # Уровень логирование

llm:
  path:                         # Путь до LLM модели
  n_threads:                    # Количество потоков для работы модели
  n_ctx:                        # Длина контекста

embedding:
  path:                         # Путь до Embedding модели
  model_name:                   # Название модели
