version: "3.9"

services:

  athena:
    build: .
    container_name: model_service
    image: athena
    ports:
      - "50051:50051"
    volumes:
      - ./model_service/models:/app/model_service/models
    restart: always